// Generated by npm run sync from tarot-room/deck.js.
const majors = ['愚者','魔术师','女祭司','女皇','皇帝','教皇','恋人','战车','力量','隐者','命运之轮','正义','倒吊人','死神','节制','恶魔','高塔','星星','月亮','太阳','审判','世界'];
const ranks = ['王牌','二','三','四','五','六','七','八','九','十','侍者','骑士','皇后','国王'];
const deck = [
  ...majors.map((name,i) => ({id:`ar${String(i).padStart(2,'0')}`,name})),
  ...[['wa','权杖'],['cu','圣杯'],['sw','宝剑'],['pe','钱币']].flatMap(([prefix,name]) => ranks.map((rank,i) => ({id:`${prefix}${i+1}`,name:name+rank})))
];
const spreads = {
  timeline: ['过去','现在','未来'],
  relationship: ['你带来的部分','关系呈现的部分','值得看见的课题'],
  work: ['当前现况','隐藏阻力','可行方向']
};
function shuffledDeck(random = Math.random) {
  const cards = deck.map(card => ({...card,reversed:random()<.5}));
  for(let i=cards.length-1;i>0;i--) {const j=Math.floor(random()*(i+1));[cards[i],cards[j]]=[cards[j],cards[i]];}
  return cards;
}
function cardPlacement(index) {
  const t=index/77, a=(t-.5)*2.12;
  return {
    x:Math.sin(a)*7.05,
    z:.40+(1-Math.cos(a))*3.9+Math.sin(index*1.71)*.014,
    rotation:-a*.60+Math.sin(index*2.13)*.009
  };
}

const SPREADS = spreads;
const SPREAD_LABELS = Object.freeze({
  timeline: '时间线',
  relationship: '感情',
  work: '工作'
});
const DEFAULT_SPREAD = 'timeline';
const SPREAD_BRIEFS = Object.freeze({
  timeline: '过去是已形成的背景，现在是当下状态，未来是现有条件持续下去的趋势；不要把未来写成确定事件或日期。',
  relationship: '依次看用户带来的部分、关系中呈现的互动、值得看见的课题；不要把这三张牌改成时间线，也不能用牌证明对方的秘密想法。',
  work: '依次看当前现况、隐藏阻力、可行方向；结合任务、协作、能力和资源谈选择，不承诺录用、收益或成功。'
});
function getSpreadPositions(spreadId) {
  return SPREADS[spreadId] || SPREADS[DEFAULT_SPREAD];
}
function getSpreadBrief(spreadId) {
  return SPREAD_BRIEFS[spreadId] || SPREAD_BRIEFS[DEFAULT_SPREAD];
}
function listSpreads() {
  return Object.keys(SPREADS).map((id) => ({id, label: SPREAD_LABELS[id] || id, positions: SPREADS[id]}));
}

module.exports = {
  deck,
  shuffledDeck,
  cardPlacement,
  spreads,
  SPREADS,
  SPREAD_LABELS,
  SPREAD_BRIEFS,
  DEFAULT_SPREAD,
  getSpreadPositions,
  getSpreadBrief,
  listSpreads
};
